### ISSUE TITLE
PuppetDB query error 404 on puppet query events 

### ISSUE THREAD

**Issue by mawi001** [dalen/puppet-puppetdbquery#39]
Hi, 

I'm having problems getting 'puppet query events' to work. I want to get all events from 'class[puppet]' in the last day. 

```
puppetmaster  ~ # puppet query events --since='1 day ago' --until now 'class[puppet]'
Error: PuppetDB query error: [404] Not Found, query: ["and",[">","timestamp","2015-01-22T10:42:02.000Z"],["<","timestamp","2015-01-23T10:42:03.000Z"],["or",["=","certname","i-am-anonymized"],["=","certname","i-am-anonymized"],["=","certname","i-am-anonymized"],["=","certname","i-am-anonymized"],["=","certname","i-am-anonymized"],["=","certname","i-am-anonymized"],["=","certname","i-am-anonymized"],["=","certname","i-am-anonymized"],["=","certname","i-am-anonymized"],["=","certname","i-am-anonymized"],["=","certname","i-am-anonymized"],["=","certname","i-am-anonymized"],["=","certname","i-am-anonymized"],["=","certname","i-am-anonymized"],["=","certname","i-am-anonymized"],["=","certname","i-am-anonymized"],["=","certname","i-am-anonymized"],["=","certname","i-am-anonymized"],["=","certname","i-am-anonymized"],["=","certname","i-am-anonymized"]]]
Error: Try 'puppet help query events' for usage
puppetmaster ~ # 
```

certnames are anonymized

using: 
puppetdbquery: 1.5.3 / be650dc 
puppet opensource: 3.7.1
puppetdb: puppetdb-2.2.2-1.el6.noarch

I see no nothing related in puppetdb.log during query time. 
I think I have the query right, I get partial results, put also an error which I cannot explain. 

Any help will be really appreciated!

Martin

**Comment by dalen** [comment]
Actually the event query is a bit rudimentary, the query is actually only a host filter, so this would try to query for all events on nodes with the class 'puppet'.

Not sure why it gives a 404 though.
Also in the PuppetDB v3 API there's no really great way to do this so it queries for a list of nodes first and then for a list of events, as the events endpoint doesn't support select-resources subqueries in v3 API. I'll improve that as soon as v4 gets released as stable.

**Comment by mawi001** [comment]
@dalen , Thanks for you reply. It would be nice if this can be improved when v4 api gets released. I have some use cases which I will store on the shelf until this is ready.

**Comment by trevor-vaughan** [comment]
@mawi001 @dalen Hi All! I did some poking about and it turns out that with the new version of PuppetDB, the 'experimental' interface is gone and 'v3' should be used instead.

I'll send over a PR in a few minutes to fix this.

**Comment by mawi001** [comment]
@trevor-vaughan Good poking! 
@dalen can this be merged?

**Comment by dalen** [comment]
merged the PR, so closing this. Will try to fix that chronic issue as well before releasing.
