### ISSUE TITLE
Query by resource tag

### ISSUE THREAD

**Issue by halfninja** [dalen/puppet-puppetdbquery#41]
I'd like to do this query

    Class[Profile::Elasticsearch] { tag="es_cluster_name_xyz" }

But the resulting query treats it like a parameter, e.g.

    ["=",["parameter","tag"],"es_cluster_name_xyz"]

It would be great if it could understand `tag` and do this instead

    ["=","tag","es_cluster_name_xyz"]

**Comment by dalen** [comment]
Fixed by merging the PR now.
