### ISSUE TITLE
Stuck getting started

### ISSUE THREAD

**Issue by jflorian** [dalen/puppet-puppetdbquery#44]
I just installed your module and was trying to do some CLI queries, but I keep getting an error.  For example:

$  puppet query nodes '(Package[httpd])'
Error: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read finished A
Error: Try 'puppet help query nodes' for usage

I tried the --debug option and can see that this error occurs immediately after creating the connection to my PuppetDB server, but I'm lost otherwise.

**Comment by dalen** [comment]
hmm, do you have the puppetdb-terminus setup and working on this host, with certificates and all?

**Comment by halfninja** [comment]
The PuppetDB logs may have more information - that will complain if a valid client certificate isn't provided.

**Comment by dalen** [comment]
Closing this issue for now. Please reopen if you're still having issued with the latest versions.

**Comment by robinbowes** [comment]
I was hitting the same error, and it was because I was running as a non-root user who didn't have access to the signed certs used by the puppet agent on the node in question.
