### ISSUE TITLE
Enhancement: support structured facts

### ISSUE THREAD

**Issue by faxm0dem** [dalen/puppet-puppetdbquery#46]
It seems not possible to query structured facts:

```
☠ puppet query nodes '(os.name=Debian)'
Error: can not match: '.name=Debian)'
Error: Try 'puppet help query nodes' for usage
```

**Comment by dalen** [comment]
This works in the JavaScript version I made, but it requires the v4 PuppetDB API which is still experimental. So I will wait until a stable release of that API is out before making a version that supports it.
There are several planned changes to the API before it becomes stable, to be released in PuppetDB 3.0.

**Comment by faxm0dem** [comment]
Fair enough, thanks!

**Comment by dalen** [comment]
I just added support for this in the master branch with commit 478f09a8cc438880749885adc8c64fcdb05e79d2

Will update the README with the new query syntax before releasing though, likely tomorrow.

**Comment by faxm0dem** [comment]
Thanks!
