### ISSUE TITLE
Possible incorrect URL encoding of query parameters

### ISSUE THREAD

**Issue by cydergoth** [dalen/puppet-puppetdbquery#50]
When performing a query like "Class['Rabbitmq']{erlang_cookie='jkdgfh+dhj'}" the CURL output from puppetdb shows the cookie value populated correctly,  but a puppet query nodes .. command fails to find the nodes. Removing the "+" from the cookie corrects this issue. I suspect a URL encoding problem.

**Comment by dalen** [comment]
That is a bit odd, it uses `URI.escape`  but also that gives me this result:

```
irb(main):001:0> require 'uri'
=> true
irb(main):002:0> URI.escape '+'
=> "+"
```

Sorry about the delay on getting back to this btw.

**Comment by cydergoth** [comment]
Closing as very old
