### ISSUE TITLE
The 'events' command in the Face should fail if the 'chronic' Gem is not installed.

### ISSUE THREAD

**Issue by trevor-vaughan** [dalen/puppet-puppetdbquery#54]
Presently, if 'chronic' is not installed on the system, any query using the 'events' command in the Face will fail with exit status '1'.

However, there will be no additional output which makes debugging this issue difficult.

Request that an error be thrown if the 'chronic' Gem is not installed.

**Comment by mawi001** [comment]
Hi @trevor-vaughan I also found this when events was not giving any output. I found a blogpost somewhere hidden on the internet that indicated that 'chronic' was a requirement for events command. 
Making this more verbose would definitely save time.

**Comment by dalen** [comment]
This was fixed in 183404615c480f7a2c4a2d4f3b49668146492836
