### ISSUE TITLE
Support for the v4 api ?

### ISSUE THREAD

**Issue by Ziaunys** [dalen/puppet-puppetdbquery#59]
PuppetDB 3.1 no longer supports the v1, v2, and v3 API versions so I was wondering if there are plans to add support for v4.

**Comment by acidprime** [comment]
Maybe something like this?
```
      # Logic to support PuppetDB API versions 3 and 4
      # and the associated PuppetDB terminus interfaces
      if Puppet::Util::Puppetdb.config.respond_to?("server_urls")
        uri = URI(Puppet::Util::Puppetdb.config.server_urls.first)
        server = uri.host
        port = uri.port
        endpoint = "/pdb/query/v4/resources"
      else
        server = Puppet::Util::Puppetdb.server
        port = Puppet::Util::Puppetdb.port
        endpoint = "/v3/resources"
      end
```

**Comment by natemccurdy** [comment]
Will also need to change all instances os `select-` to `select_` as the key names have changed in v4.

**Comment by riton** [comment]
:+1: . Is there any plan to support the v4 API in a near future ?

**Comment by pyther** [comment]
Looks like partial support was added in e20eea84d2d6ee29698625c19de727c089f414e4.

I submitted pull request https://github.com/dalen/puppet-puppetdbquery/pull/62 

It replaces 
```
Puppet::Util:Puppetdb.server
Puppet::Util:Puppetdb.port
```
 with
```
uri = URI(Puppet::Util::Puppetdb.config.server_urls.first)
uri.host
uri.port
```

**Comment by dalen** [comment]
I just pushed the release of 2.0.0 now. And it actually has full support for structured facts as well :)
Hope it works well (it does in my testing). But report any bugs you find.
