### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mattbostock** [dalen/puppet-puppetdbquery#60]
Hello,

Could you please release a new version so that I can take advantage of #56, currently on `master`?

Thanks,
Matt

**Comment by dalen** [comment]
There's a bunch of other changes on master to make it use the new V4 API in PuppetDB 3.x. I'm finishing up some API changes I'd like to make before releasing.

So the new release will be 2.0.0 and not backwards compatible. After doing that I suppose I could backport this feature to a 1.x branch though.

**Comment by mattbostock** [comment]
Thanks @dalen.
