### ISSUE TITLE
query_facts calls non-existent method "facts" of PuppetDB::Connection

### ISSUE THREAD

**Issue by ayohrling** [dalen/puppet-puppetdbquery#68]
The query_facts function makes a connection with the PuppetDB::Connection class, then attempts to call a 'facts' method when it makes its call. The method doesn't exist, which results in the following output:

Error: Evaluation Error: Error while evaluating a Function Call, undefined method `facts' for #<PuppetDB::Connection:0x00000003207b98>

**Comment by dalen** [comment]
Thanks for the fixes. I've merged them now and releasing 2.0.2 with them.
