### ISSUE TITLE
Allow for a retrieval of all active nodes

### ISSUE THREAD

**Issue by jasonhancock** [dalen/puppet-puppetdbquery#7]
Prior to version 0.1.0, you could retrieve the list of all active nodes by doing something like this:
```
$active_nodes = pdbnodequery(['=',['node','active'],true])
```

With the changes introduced in 5426aa7d8576d6a9011832d6219176831626b060, you now have to do this to achive the same thing:

```
$active_nodes = pdbnodequery_all(['=',['node','active'],true])
```

However, it would be nice to only have to do this:
```
$active_nodes = pdbnodequery()
```

Or, I would be happy with:
```
$active_nodes = pdbnodequery([])
```
The last two examples fail with this error message:
```
err: Could not retrieve catalog from remote server: Error 400 on SERVER: PuppetDB query error: [500] Server Error at /etc/puppet/path/to/some/manifest/init.pp:47 on node server.example.com
```

There's obviously a working workaround, so I can understand if you don't want to update the code for this edge case. If that's the case, would you accept a pull request to update the documentation with an example for how to retrieve a list of active nodes?

**Comment by dalen** [comment]
Well, this works in the latest versions, Although using the `query_nodes` function instead. Closing.
