### ISSUE TITLE
Is this module still being maintained?

### ISSUE THREAD

**Issue by mcasper** [dalen/puppet-puppetdbquery#90]
@dalen Are you still maintaining this module?

**Comment by Sher-Chowdhury** [comment]
@dalen I just discovered this module when reading the book 'Extending Puppet' by Alessandro Franceschi. I'm sure a lot of people are finding this module via this book. I would really like to make use of this module. Therefore could you advise if this module is still being maintained?

**Comment by ghstwhl** [comment]
If you look at the commit history, you can answer your own question. 

-Sent from my Pip-Boy 3000

**Comment by Sher-Chowdhury** [comment]
I did check the commit history and it looks like the last commit was done just over 4 months ago, which is a quite a long time given there a couple of PR outstanding. But no worries, I'll give this module a try anyway.

**Comment by ghstwhl** [comment]
Well, bugger. It has been that long. Time flies...  

-Sent from my Pip-Boy 3000

**Comment by dalen** [comment]
Hi, sorry about the late reply. I'm still maintaining it, I've just been a bit busy with my new job etc lately. But I'll take a look at the PRs and stuff today and the next couple of days.
